version: "2"
linters:
  enable:
    - errcheck
    - exhaustive
    - exhaustruct
    - forbidigo
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    - nlreturn
    - paralleltest
    - revive
    - sloglint
    - staticcheck
    - unused
